#---------------------------------------------------------------------#
#     _____ _ _   _                     ____              _           #
#    / ____(_) | (_)                   |  _ \            | |          #
#   | |     _| |_ _ _______ _ __  ___  | |_) | ___   ___ | | _____    #
#   | |    | | __| |_  / _ \ '_ \/ __| |  _ < / _ \ / _ \| |/ / __|   #
#   | |____| | |_| |/ /  __/ | | \__ \ | |_) | (_) | (_) |   <\__ \   #
#    \_____|_|\__|_/___\___|_| |_|___/ |____/ \___/ \___/|_|\_\___/   #
#                                                                     #
#---------------------------------------------------------------------#

version: 9 #DO NOT CHANGE/REMOVE
metrics: true
update_check: true
lang:
  header: "&f[&6CitizensBooks&f] &r"
  no_permission: "&cYou don't have permission!"
  config_reloaded: "&aConfig reloaded."
  set_book_successfully: "&aYou have set the book for %npc%&a!"
  set_join_book_successfully: "&aYou have set the join book!"
  removed_book_successfully: "&aYou have removed the book for %npc%&a!"
  removed_join_book_successfully: "&aYou have removed the join book!"
  no_npc_selected: "&cYou need to have an NPC selected!"
  no_book_in_hand: "&cYou need to have a written book in your hand!"
  no_item_in_hand: "&cYou need to have an item in your hand!"
  no_book_for_npc: "&cThis NPC doesn't have a book!"
  no_book_for_filter: "&cThis filter doesn't have a book!"
  filter_saved: "&aFilter %filter_name% was saved."
  filter_removed: "&aFilter %filter_name% was removed."
  book_recived: "&aYou recived the book in your inventory!"
  citizens_not_enabled: "&cCitizens plugin is not enabled! This command requires Citizens to be installed!"
  nbtapi_not_enabled: "&cNBTAPI plugin is not enabled! This command requires NBTAPI to be installed!"
  set_custom_command_successfully: "&aCommand %command% has been set!"
  removed_custom_command_successfully: "&aCommand %command% has been removed!"
  console_cannot_use_command: "&cOnly players can use this command!"
  new_version_available: "&aA new version of CitizensBooks is available!"
  player_not_found: "&cPlayer not found!"
  filter_not_found: "&cFilter not found!"
  filter_applied_to_item: "&aFilter &b%filter_name% &ahas been applied to your holding item."
  filter_removed_from_item: "&aThe filter has been removed from your holding item."
  filter_name_invalid: "&cThe filter name should only contain letters, numbers, dashes and underscores!"
  command_name_invalid: "&cThe command name should only contain letters, numbers, dashes and underscores!"
  usage:
    help: "&aUsage: &f/npcbook help [page]"
    openbook: "&aUsage: &f/npcbook openbook"
    forceopen: "&aUsage: &f/npcbook forceopen <filter name> <player>"
    setcmd: "&aUsage: &f/npcbook setcmd <command> <filter name> [permission]"
    remcmd: "&aUsage: &f/npcbook remcmd <command>"
    setjoin: "&aUsage: &f/npcbook setjoin"
    remjoin: "&aUsage: &f/npcbook remjoin"
    filter:
      set: "&aUsage: &f/npcbook filter set <filter name>"
      remove: "&aUsage: &f/npcbook filter remove <filter name>"
      getbook: "&aUsage: &f/npcbook filter getbook <filter name>"
    actionitem:
      set: "&aUsage: &f/npcbook actionitem set <filter name> [right/left]"
      remove: "&aUsage: &f/npcbook actionitem remove [right/left]"
    npc:
      set: "&aUsage: &f/npcbook npc set [right/left]"
      remove: "&aUsage: &f/npcbook npc remove [right/left]"
      getbook: "&aUsage: &f/npcbook npc getbook [right/left]"
  help:
    info: "&e<    &6Commands and Usage &f| &6Page index (%page%/3) &e    >"
    arguments: "&f(&c<> &f= &erequired argument&f, &c[] &f= &eoptional argument&f)"
    help: "&f/npcbook help [page] $ &9Show help page."
    about: "&f/npcbook about $ &9Informations about the plugin."
    openbook: "&f/npcbook openbook $ &9Opens a writen book."
    forceopen: "&f/npcbook forceopen <filter name> <player> $ &9Force a player to open a book."
    reload: "&f/npcbook reload $ &9Reload the config file."
    setcmd: "&f/npcbook setcmd <command> <filter name> $ &9Sets a custom command by the given filter name."
    remcmd: "&f/npcbook remcmd <command> $ &9Remove the custom command."
    setjoin: "&f/npcbook setjoin $ &9Set the join book."
    remjoin: "&f/npcbook remjoin $ &9Remove the join book."
    filter:
      set: "&f/npcbook filter set <filter name> $ &9Create a filter with the given name."
      remove: "&f/npcbook filter remove <filter name> $ &9Remove a filter with the given name."
      getbook: "&f/npcbook filter getbook <filter name> $ &9Get the book of the filter with the given name."
    actionitem:
      set: "&f/npcbook actionitem set <filter name> [right/left] $ &9Put a filter on the item you hold."
      remove: "&f/npcbook actionitem remove [right/left] $ &9Remove the filter from the item you hold."
    npc:
      set: "&f/npcbook npc set [right/left] $ &9Set a book for npc."
      remove: "&f/npcbook npc remove [right/left] $ &9Remove the book from npc."
      getbook: "&f/npcbook npc getbook [right/left] $ &9Get the book of npc."
save: { }
commands:
  hello:
    filter_name: hello_world
    permission: perm.hello_world
join_book_enabled: false
join_book_last_change: 0 #DO NOT MANUALLY EDIT THIS
join_book_always_show: false
join_book_enable_delay: false
join_book_delay: 0 # in ticks (20 ticks = 1 second) - if AuthMe is enabled, this will be ignored!
join_book_last_seen_by_players: { }
database:
  type: "json" # json, sqlite, mysql
  threads: 2
  sqlite:
    file_name: "storage.db"
  mysql:
    user: "user"
    password: "password"
    ip: "localhost"
    port: 3306
    name: "db_name"
    enable_ssl: false
    table_prefix: "cbooks_"
    server_name: "default"