name: CitizensBooks
version: ${project.version}
author: NicoNekoDev
main: ro.nicuch.citizensbooks.CitizensBooksPlugin
softdepend: [ PlaceholderAPI, Citizens, LuckPerms, Vault, AuthMe, Authme, NBTAPI ]
website: https://www.spigotmc.org/resources/citizensbooks.37465/
api-version: 1.13
commands:
  npcbook:
    description: Basic CitizensBooks command.
    permission: npcbook.command.*
permissions:
  npcbook.*:
    children:
      npcbook.command.help: true
      npcbook.command.npc.set: true
      npcbook.command.npc.remove: true
      npcbook.command.npc.getbook: true
      npcbook.command.openbook: true
      npcbook.command.closebook: true
      npcbook.command.reload: true
      npcbook.command.setcmd: true
      npcbook.command.remcmd: true
      npcbook.command.filter.set: true
      npcbook.command.filter.remove: true
      npcbook.command.filter.getbook: true
      npcbook.command.forcedecrypt: true
      npcbook.command.forceopen: true
      npcbook.command.actionitem.set: true
      npcbook.command.actionitem.remove: true
      npcbook.command.setjoin: true
      npcbook.command.remjoin: true
      npcbook.nojoinbook: true
      npcbook.notify: true
  npcbook.command.*:
    children:
      npcbook.command.help: true
      npcbook.command.npc.set: true
      npcbook.command.npc.remove: true
      npcbook.command.npc.getbook: true
      npcbook.command.openbook: true
      npcbook.command.closebook: true
      npcbook.command.reload: true
      npcbook.command.setcmd: true
      npcbook.command.remcmd: true
      npcbook.command.filter.set: true
      npcbook.command.filter.remove: true
      npcbook.command.filter.getbook: true
      npcbook.command.forcedecrypt: true
      npcbook.command.forceopen: true
      npcbook.command.actionitem.set: true
      npcbook.command.actionitem.remove: true
      npcbook.command.setjoin: true
      npcbook.command.remjoin: true
  npcbook.command.filter.*:
    children:
      npcbook.command.filter.set: true
      npcbook.command.filter.remove: true
      npcbook.command.filter.getbook: true
  npcbook.command.actionitem.*:
    children:
      npcbook.command.actionitem.set: true
      npcbook.command.actionitem.remove: true
  npcbook.command.npc.*:
    children:
      npcbook.command.npc.set: true
      npcbook.command.npc.remove: true
      npcbook.command.npc.getbook: true
  npcbook.command.help:
    default: false
  npcbook.command.npc.set:
    default: false
  npcbook.command.npc.remove:
    default: false
  npcbook.command.npc.getbook:
    default: false
  npcbook.command.openbook:
    default: false
  npcbook.command.reload:
    default: false
  npcbook.command.setcmd:
    default: false
  npcbook.command.remcmd:
    default: false
  npcbook.command.filter.set:
    default: false
  npcbook.command.filter.remove:
    default: false
  npcbook.command.filter.getbook:
    default: false
  npcbook.command.actionitem.set:
    default: false
  npcbook.command.actionitem.remove:
    default: false
  npcbook.command.setjoin:
    default: false
  npcbook.command.remjoin:
    default: false
  npcbook.command.closebook:
    default: false
  npcbook.notify:
    default: op
  npcbook.nojoinbook:
    default: false