#######################################################################
#     _____ _ _   _                     ____              _           #
#    / ____(_) | (_)                   |  _ \            | |          #
#   | |     _| |_ _ _______ _ __  ___  | |_) | ___   ___ | | _____    #
#   | |    | | __| |_  / _ \ '_ \/ __| |  _ < / _ \ / _ \| |/ / __|   #
#   | |____| | |_| |/ /  __/ | | \__ \ | |_) | (_) | (_) |   <\__ \   #
#    \_____|_|\__|_/___\___|_| |_|___/ |____/ \___/ \___/|_|\_\___/   #
#                                                                     #
#######################################################################

version: 7 #DO NOT CHANGE/REMOVE
metrics: true
update_check: true
lang:
  header: "&f[&6CitizensBooks&f] &r"
  no_permission: "&cYou don''t have permission!"
  config_reloaded: "&aConfig reloaded."
  set_book_successfully: "&aYou have set the book for %npc%&a!"
  remove_book_successfully: "&aYou have removed the book for %npc%&a!"
  no_npc_selected: "&cYou need to have an NPC selected!"
  no_book_in_hand: "&cYou need to have a book in your hand!"
  no_book_for_npc: "&cThis NPC doesn''t have a book!"
  no_book_for_filter: "&cThis filter doesn''t have a book!"
  filter_saved: "&aFilter %filter_name% was saved."
  filter_removed: "&aFilter %filter_name% was removed."
  book_recived: "&aYou recived the book in your inventory!"
  citizens_not_enabled: "&cCitizens plugin is not enabled!"
  set_custom_command_successfully: "&aCommand %command% has been set!"
  remove_custom_command_successfully: "&aCommand %command% has been removed!"
  console_cannot_use_command: "&cYou have to be a player if you want to use this command!"
  new_version_available: "&aA new version of CitizensBooks is available!"
  usage:
    set: "&aUsage: &f/npcbook set"
    remove: "&aUsage: &f/npcbook remove"
    getbook: "&aUsage: &f/npcbook getbook"
    openbook: "&aUsage: &f/npcbook openbook"
    setcmd: "&aUsage: &f/npcbook setcmd <command> <filter name>"
    remcmd: "&aUsage: &f/npcbook remcmd <command>"
    filter:
      set: "&aUsage: &f/npcbook filter set <filter name>"
      remove: "&aUsage: &f/npcbook filter remove <filter name>"
      getbook: "&aUsage: &f/npcbook filter getbook <filter name>"
  help:
    about: "&f/npcbook about &c- &9Informations about plugin."
    set: "&f/npcbook set &c- &9Set book for npc."
    remove: "&f/npcbook remove &c- &9Remove book for npc."
    getbook: "&f/npcbook getbook &c- &9Get the book of npc."
    openbook: "&f/npcbook openbook &c- &9Open a writen book."
    reload: "&f/npcbook reload &c- &9Reload config file."
    setcmd: "&f/npcbook setcmd <command> <filter name> &c- &9Set command by the given filter name."
    remcmd: "&f/npcbook remcmd <command> &c- &9Remove command."
    filter:
       set: "&f/npcbook filter set <filter name> &c- &9Set a filter by the given name."
       remove: "&f/npcbook filter remove <filter name> &c- &9Remove a filter by the given name."
       getbook: "&f/npcbook filter getbook <filter name> &c- &9Get the book of filter by the given name."
filters: {} 
save: {} 
commands:
  helloworld: "test1"