name: ${project.artifactId}
version: ${project.version}
author: nicuch
main: ro.nicuch.citizensbooks.CitizensBooksPlugin
softdepend: [PlaceholderAPI, Citizens, Vault]
commands:
  npcbook:
    description: Basic CitizensBooks command.