name: AstralBooks
version: ${project.version}
author: NicoNekoDev
main: ro.niconeko.astralbooks.AstralBooksPlugin
softdepend: [ PlaceholderAPI, Citizens, LuckPerms, Vault, AuthMe, Authme, CitizensBooks ]
website: https://www.spigotmc.org/resources/astralbooks-a-book-for-everything.37465/
api-version: 1.13