name: Java CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Installing Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          check-latest: true

      - name: Install spigot (1.8 -> 1.16)
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v8.sh
          ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v8.sh
        shell: bash

      - name: Installing Java 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          check-latest: true

      - name: Install spigot... (1.17 -> latest)
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v16.sh
          ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v16.sh
        shell: bash

      - name: Installing Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Build CitizensBooks with Maven
        run: mvn -B package --file pom.xml
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Installing Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}