name: Build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Cache local Maven repository
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/scripts') }}
          restore-keys: |
            maven-

      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          check-latest: true

      - name: Install spigot (1.8 -> 1.16)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/scripts/buildtools-java8.sh
          ${GITHUB_WORKSPACE}/.github/scripts/buildtools-java8.sh
        shell: bash

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true

      - name: Install spigot... (1.17 -> latest)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/scripts/buildtools-java17.sh
          ${GITHUB_WORKSPACE}/.github/scripts/buildtools-java17.sh
        shell: bash

      - name: Install spigot... (1.18 -> latest)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v17.sh
          ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v17.sh
        shell: bash

      - name: Build CitizensBooks with Maven
        run: mvn --batch-mode package -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}