name: Java CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: /.scripts/
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          check-latest: true
      - name: Install spigot...
        if: steps.cache.outputs.cache-hit != 'true'
        run: /buildtools-install-v8.sh
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          check-latest: true
      - run: /buildtools-install-v16.sh
      - name: Build with Maven
        run: mvn -B package --file pom.xml
