name: Java CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          check-latest: true
      - run: ~/.scripts/buildtools-install-v8
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          check-latest: true
      - run: ~/.scripts/buildtools-install-v16
      - name: Build with Maven
        run: mvn -B package --file pom.xml
