name: Publish
on:
  release:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          check-latest: true
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Cache local Maven repository
        id: cache-v8
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/buildtools-install-v8.sh') }}

      - name: Cache local Maven repository
        id: cache-v16
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/buildtools-install-v16.sh') }}

      - name: Build & Deploy CitizensBooks with Maven
        run: mvn -B package --file pom.xml deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}