name: Java CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Installing Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          check-latest: true

      - name: Load caching v8
        uses: actions/cache@v2
        id: cache-v8
        with:
          path: ~/cache
          key: ${{ runner.os }}-node-${{ hashFiles('${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v8.sh') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install spigot (1.8 -> 1.16)
        if: steps.cache-v8.outputs.cache-hit != 'true'
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v8.sh
          ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v8.sh
        shell: bash

      - name: Installing Java 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          check-latest: true

      - name: Load caching v16
        uses: actions/cache@v2
        id: cache-v16
        with:
          path: ~/cache
          key: ${{ runner.os }}-node-${{ hashFiles('${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v16.sh') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install spigot... (1.17 -> latest)
        if: steps.cache-v16.outputs.cache-hit != 'true'
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v16.sh
          ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v8.sh
        shell: bash

      - name: Installing Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Build CitizensBooks with Maven
        run: mvn -B package --file pom.xml
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Installing Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Deploy CitizensBooks to Github Package Registry
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --settings settings.xml --file pom.xml deploy