name: Java CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Installing Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          check-latest: true

      - name: Cache local Maven repository
        id: cache-v8
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/buildtools-install-v8.sh') }}

      - name: Install spigot (1.8 -> 1.16)
        if: steps.cache-v8.outputs.cache-hit != 'true'
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v8.sh
          ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v8.sh
        shell: bash

      - name: Installing Java 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          check-latest: true

      - name: Cache local Maven repository
        id: cache-v16
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/buildtools-install-v16.sh') }}

      - name: Install spigot... (1.17 -> latest)
        if: steps.cache-v16.outputs.cache-hit != 'true'
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v16.sh
          ${GITHUB_WORKSPACE}/.github/scripts/buildtools-install-v16.sh
        shell: bash

      - name: Build CitizensBooks with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}